//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GYMDBEntities4 : DbContext
    {
        public GYMDBEntities4()
            : base("name=GYMDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MembershipTB> MembershipTBs { get; set; }
        public virtual DbSet<MemberTB> MemberTBs { get; set; }
        public virtual DbSet<TrainerTB> TrainerTBs { get; set; }
        public virtual DbSet<VisitorTB> VisitorTBs { get; set; }
        public virtual DbSet<TransactionTB> TransactionTBs { get; set; }
    }
}
