//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipTB
    {
        public int ID { get; set; }
        public string MembershipPlan { get; set; }
        public int Price { get; set; }
        public int Days { get; set; }
        public string Type { get; set; }
    }
}
