//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerTB
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime JoinDate { get; set; }
        public System.DateTime DOB { get; set; }
        public string Address { get; set; }
        public int Experience { get; set; }
    }
}
