//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTB
    {
        public int ID { get; set; }
        public string Membership { get; set; }
        public int OfferPrice { get; set; }
        public int PaidAmount { get; set; }
        public int DueAmount { get; set; }
        public System.DateTime DueDate { get; set; }
        public int M_ID { get; set; }
        public string Trainer { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<System.DateTime> MembershipEndDate { get; set; }
    
        public virtual MemberTB MemberTB { get; set; }
    }
}
